// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windetta.Identity.Infrastructure.Sagas;

#nullable disable

namespace Windetta.Identity.Infrastructure.Data.Migrations.SagasDb
{
    [DbContext(typeof(SagasDbContext))]
    partial class SagasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Windetta.Identity.Infrastructure.Sagas.NewUserFlow", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("NewUserFlow");
                });
#pragma warning restore 612, 618
        }
    }
}
