// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windetta.Wallet.Data;

#nullable disable

namespace Windetta.Wallet.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20231009070604_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Windetta.Wallet.Domain.UserWallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("HeldBalance")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.WalletKeysSet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.WalletKeysSet", b =>
                {
                    b.HasOne("Windetta.Wallet.Domain.UserWallet", "Wallet")
                        .WithOne("WalletKeys")
                        .HasForeignKey("Windetta.Wallet.Domain.WalletKeysSet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.UserWallet", b =>
                {
                    b.Navigation("WalletKeys")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
