// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windetta.TonTxns.Infrastructure.Sagas;

#nullable disable

namespace Windetta.TonTxns.Migrations.SagasDb
{
    [DbContext(typeof(SagasDbContext))]
    [Migration("20240427085107_SagaInitial")]
    partial class SagaInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Windetta.TonTxns.Infrastructure.Sagas.TonWithdrawFlow", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ExpirationTokenId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FailReason")
                        .HasColumnType("longtext");

                    b.Property<ulong>("Nanotons")
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("TonWithdrawFlow");
                });
#pragma warning restore 612, 618
        }
    }
}
