// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windetta.TonTxns.Infrastructure.Data;

#nullable disable

namespace Windetta.TonTxns.Migrations
{
    [DbContext(typeof(TonDbContext))]
    [Migration("20231103123134_AddedTransactionsTable")]
    partial class AddedTransactionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Windetta.TonTxns.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<sbyte>("Status")
                        .HasColumnType("TINYINT");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("BIGINT");

                    b.Property<short>("TransfersCount")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
