// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windetta.Wallet.Infrastructure.Data;

#nullable disable

namespace Windetta.Wallet.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    partial class WalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Windetta.Wallet.Domain.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<long>("Amount")
                        .HasColumnType("BIGINT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("DATETIME(6)");

                    b.Property<sbyte>("Type")
                        .HasColumnType("TINYINT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.UserBalance", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("CHAR(36)");

                    b.Property<long>("Amount")
                        .HasColumnType("BIGINT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<long>("HeldAmount")
                        .HasColumnType("BIGINT");

                    b.HasKey("WalletId");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.UserWallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.UserBalance", b =>
                {
                    b.HasOne("Windetta.Wallet.Domain.UserWallet", null)
                        .WithMany("Balances")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Windetta.Wallet.Domain.UserWallet", b =>
                {
                    b.Navigation("Balances");
                });
#pragma warning restore 612, 618
        }
    }
}
